-- Drop tables if they exist to ensure clean definitions
DROP TABLE IF EXISTS football.match_stats CASCADE;
DROP TABLE IF EXISTS football.matches CASCADE;
DROP TABLE IF EXISTS football.team CASCADE;

-- Create the schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS football;

-- Create the team table
CREATE TABLE football.team (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    logo VARCHAR(255)
);

-- Create the matches table
CREATE TABLE football.matches (
    id BIGINT PRIMARY KEY,
    season INTEGER NOT NULL,
    match_date_time TIMESTAMP NOT NULL,
    is_finished BOOLEAN
);

-- Create the match_stats table with auto-generated ID
CREATE TABLE football.match_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- auto-incrementing ID
    team_id BIGINT NOT NULL,
    match_id BIGINT NOT NULL,
    is_guest BOOLEAN,
    score INTEGER,
    is_winner BOOLEAN,
    goals INTEGER,
    CONSTRAINT fk_team FOREIGN KEY (team_id) REFERENCES football.team(id),
    CONSTRAINT fk_match FOREIGN KEY (match_id) REFERENCES football.matches(id)
    );

-- Clear all tables (not strictly needed after drop, but safe)
TRUNCATE TABLE football.match_stats RESTART IDENTITY CASCADE;
TRUNCATE TABLE football.matches RESTART IDENTITY CASCADE;
TRUNCATE TABLE football.team RESTART IDENTITY CASCADE;

-- Insert test teams
INSERT INTO football.team (id, name) VALUES
    (1, 'Team A'),
    (2, 'Team B'),
    (3, 'Team C'),
    (4, 'Team D');

-- Insert a test match
INSERT INTO football.matches (id, season, match_date_time, is_finished) VALUES
    (1, 2025, '2026-03-31 13:24:13', true);

-- Insert match statistics for the test match
INSERT INTO football.match_stats (team_id, match_id, is_guest, score, is_winner, goals) VALUES
    (1, 1, false, 3, true, 2),
(   2, 1, true, 0, false, 1);