# =============================
# TEAM REQUESTS
# =============================

### Create a team
POST http://localhost:8080/api/v1/teams
Content-Type: application/json

{
  "name": "Red Dragons"
}

### Get all teams (by default)
GET http://localhost:8080/api/v1/teams

### Get all teams (with pagination)
GET http://localhost:8080/api/v1/teams?page=0&size=10

### Get a team by ID
GET http://localhost:8080/api/v1/teams/1

### Update a team
PUT http://localhost:8080/api/v1/teams/1
Content-Type: application/json

{
  "name": "Blue Tigers"
}

### Delete a team
DELETE http://localhost:8080/api/v1/teams/1

# =============================
# PLAYER REQUESTS
# =============================

### Create a player
POST http://localhost:8080/api/v1/players
Content-Type: application/json

{
  "firstName": "Lionel",
  "lastName": "Messi",
  "middleName": "Andres",
  "teamId": 1
}

### Get all players (with pagination)
GET http://localhost:8080/api/v1/players?page=0&size=10

### Get a player by ID
GET http://localhost:8080/api/v1/players/1

### Update a player
PUT http://localhost:8080/api/v1/players/1
Content-Type: application/json

{
  "firstName": "Cristiano",
  "lastName": "Ronaldo",
  "middleName": null,
  "teamId": 2
}

### Delete a player
DELETE http://localhost:8080/api/v1/players/1

### Craete a match
POST http://localhost:8080/api/v1/matches
Content-Type: application/json

{
  "season": 2025,
  "matchDate": "2025-03-12",
  "team1": {
    "id": 1,
    "isGuest": false
  },
  "team2": {
    "id": 2,
    "isGuest": true
  }
}

### Finish match with id = 3
POST http://localhost:8080/api/v1/matches/3/finish
Content-Type: application/json

{
  "team1": {
    "teamId": 1,
    "goals": 3
  },
  "team2": {
    "teamId": 2,
    "goals": 0
  }
}


